[package]
name = "gifterm"
version = "0.1.0"
edition = "2021"

[dependencies]
pixel_loop = { version = "0.1.0", default-features = false, features = ["crossterm", "image-load"] }
image = "*"
anyhow = "*"